######################################################################## 
# Code Generated By: Fortinet Corporation 
# Generated On: 05/09/2019 17:00 AM 
# Generated By: ppeczkowski@fortinet.com
########################################################################


#Generate Form Function
function generateForm {

    #  param (
        
    # )
    #region import System. assembly
    [reflection.assembly]::LoadWithPartialName("System.Windows.Forms") | Out-Null
    [reflection.assembly]::LoadWithPartialName("System.Drawing") | Out-Null
    #end region
    
    #region generate form objects
    $main_form = New-Object Windows.System.Forms.Form
    $credentialsProviderButton = New-Object System.Windows.Forms.Button 
    

    #end region
    
    

}










